### ISSUE TITLE
ImportError: No module named 'OpenPath'

### ISSUE THREAD

**Issue by joelsouza** [shagabutdinov/sublime-folder-files#3]
Installed all dependencies on `~/Library/Application Support/Sublime Text 3/Packages` cloning all dependencies repositories

QuickSearchEnhanced
FileList
OpenPath
StatusMessage

And after restarting sublime got this message

<img width="447" alt="Screen Shot 2020-10-16 at 09 38 01" src="https://user-images.githubusercontent.com/22049/96259113-7d327500-0f93-11eb-8af5-6669437d1ced.png">

```bash
error: Dependency import failed; please read readme for FolderFiles plugin for installation instructions; to disable this message remove this plugin; message: No module named 'OpenPath'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/joelsouza/Library/Application Support/Sublime Text 3/Packages/FolderFiles/commands.py", line 17, in <module>
    raise error
  File "/Users/joelsouza/Library/Application Support/Sublime Text 3/Packages/FolderFiles/commands.py", line 12, in <module>
    from OpenPath.open_path import open_path
ImportError: No module named 'OpenPath'
```

At the end of the console, this message threw my attention: 

```bash
Package Control: Removed directory for orphaned package sublime-open-path
unloading plugin sublime-open-path.open_path
```

@shagabutdinov really appreciate any kind of help on how to solve this.

**Comment by shagabutdinov** [comment]
Hey, thanks for reporting the issue! Try installing the [Open Path](https://github.com/shagabutdinov/sublime-open-path) sublime extension?
